const QUOTES = [
    // English
    "Pause. Are you working on your #1 priority?",
    "The best revenge is massive success. Keep crushing it!",
    "Do highest-priority, focused, consistent work — RIGHT NOW.",
    "Protect your time, focus and energy.",
    "Focus is saying NO to things that don't move the needle.",
    "Every second matters. Just get started and do it fast.",
    "Be aggressive about the life you want. There is no alternative to hard work.",
    "Don't get frustrated before you even begin. Just start — you'll realize how quickly it gets done.",
    "When you want success as badly as you want air when drowning, you'll get it. There is no other secret. — Socrates",
    "Just keep making baby steps — small enough to accomplish, large enough to give satisfaction.",
    "You won't rise to your intention. You'll fall to your training.",
    "3 keys of success: Know more than others. Work more than others. Expect less than others.",
    "Consistency and discipline are the two things you need to be a better you.",
    "NEVER EVER GIVE UP IN LIFE.",
    "Be so busy improving yourself that you have no time to criticize others.",
    "The hardest battle is between your old habits and your new standards.",
    "Daily non-negotiables: Speak answers loudly, Practice coding, Apply a lot.",
    "When you do hard work, stars automatically align and success comes from all fronts.",
    "Being an alpha is mastery of mind, body, communication and presence.",
    "Knowledge + confidence + execution = natural authority.",
    "What am I avoiding today?",
    "Where am I confusing motion with progress?",
    "Dopamine must have a job, or it will pick one — usually the easiest one.",
    "I need you to lock in and stop being distracted. I believe in you.",
    "Before doing anything, ask: Is it good for my body, mind, or future? If yes — do it. If no — never do it.",
    "Doing nothing is far better than doom scrolling.",
    "No doom scrolling. No junk food. Daily exercise. Deep sleep. Daily meditation.",
    "Take baby steps — small enough to accomplish, big enough to feel the progress and keep going.",
    "Is the current task valuable enough to cancel other work ? - If No, it is garbage work!",
    "Lots of things are urgent. But urgency and priority are absolutely not the same thing. Your default should be to do only your highest priority work. And then you can consider the urgency of that work to consider slightly changing the order you work on things.",
    "I must lead by example for my daughter!",
    "I must suffer one of two things: the pain of discipline or the pain of regret",
    "Nothing changes until something (or someone) pushes it to. No force = no change - Newton's 1st Law",
    "Bigger goals need bigger or more sustained effort — the size of the push has to match the size of the mass. - Newton's 2nd Law",
    "Whatever force you put out into your relationships, work, or habits, something comes back at you — often proportional. Every action has a reaction - Newton's 3rd Law",
    "Nothing moves until I push. How much I move depends on how much force I apply, relative to the size of the problem. Everything I do eventually pushes something back at me. - Life parallels of Newton's 3 laws",
    "You can reinvent yourself as many times as you need. New standards. New habits. New mindsets. It's never too late. You can change. Today, tomorrow, and as many times as it takes to create the life you want.",

    // Gujarati
    "યોગઃ કર્મશુ કૌશલમ! — કર્મમાં કુશળતા એ જ યોગ છે.",
    "કર્મ કર, ફળ ની આશા ના રાખ.",
    "તારો કંટ્રોલ ઇન્દ્રિયો પર હોવો જોઈએ — ઇન્દ્રિયો તને કંટ્રોલ કરે એ ના હોવું જોઈએ.",
    "પરફેક્શન નહીં, પ્રોગ્રેસ જોઈએ છે. ૭૦% તૈયારી પણ પૂરતી છે.",
    "આજે એક નાનું પગલું ભરજે — પણ આગળ વધ. તું કરી શકે છે. તે કર્યું પણ છે પહેલાં.",
];